using System.Text;
using System.Text.RegularExpressions;

namespace Scribe.Core;

public static class RenpyExporter
{
    private static readonly Regex Identifier = new(@"\A[A-Za-z_][A-Za-z0-9_]{0,127}\z", RegexOptions.CultureInvariant);
    private static readonly HashSet<string> Reserved = new(StringComparer.Ordinal)
    {
        "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield",
        "label", "jump", "call", "menu", "scene", "show", "hide", "image", "define", "default", "python", "init", "screen", "transform", "style", "translate", "play", "stop", "queue", "pause", "voice", "window"
    };

    public static string Generate(IEnumerable<Segment> segments, ExportOptions options, IEnumerable<ChoiceTree>? choiceTrees = null)
    {
        if (segments is null) throw new UserFacingException("没有可导出的内容，请先导入并解析文档。");
        if (options is null) throw new UserFacingException("缺少导出设置，请重新设置导出选项。");
        ValidateIdentifier(options.Label, "剧情标签");
        if (options.CharacterVariables is null) throw new UserFacingException("角色变量映射无效，请重新设置。");
        foreach (var pair in options.CharacterVariables)
        {
            if (string.IsNullOrWhiteSpace(pair.Key)) throw new UserFacingException("角色变量映射中包含空角色名，请删除或补充。");
            ValidateIdentifier(pair.Value, $"角色“{pair.Key}”对应的变量");
        }

        var allSegments = segments.Take(200_001).ToList();
        if (allSegments.Count > 200_000) throw new UserFacingException("导出的段落过多，请按章节导出。");
        var allTrees = choiceTrees?.Take(20_001).ToList() ?? [];
        if (allTrees.Count > 20_000) throw new UserFacingException("选项树内容过多，请分章节制作。");
        ChoiceTreeValidator.Validate(allTrees, allSegments, requireComplete: true);
        var before = allTrees.Where(t => t.Placement == ChoicePlacement.Before)
            .GroupBy(t => t.AnchorSegmentId, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.ToList(), StringComparer.Ordinal);
        var after = allTrees.Where(t => t.Placement == ChoicePlacement.After)
            .GroupBy(t => t.AnchorSegmentId, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.ToList(), StringComparer.Ordinal);
        var automaticVariables = BuildCharacterVariables(allSegments, allTrees, options);

        var result = new StringBuilder("# Generated by Ren'Py Scribe / Ren'Py 剧本助手\n# UTF-8。导入的特殊标点已按字面显示转义。\n");
        result.Append("# 在现有游戏中使用 call ").Append(options.Label).Append(" 调用本段。\n\n");
        result.Append("define s = Character(None)\n");
        foreach (var pair in automaticVariables)
            result.Append("define ").Append(pair.Value).Append(" = Character(\"").Append(Escape(pair.Key)).Append("\")\n");
        result.Append("\nlabel ").Append(options.Label).Append(":\n");

        void CheckOutputSize()
        {
            if (result.Length > 50_000_000) throw new UserFacingException("导出内容过大，请按章节导出。");
        }

        int included = 0;
        void EmitSegment(Segment segment, string indent)
        {
            if (segment is null) throw new UserFacingException("识别结果包含无效段落，请重新解析。");
            if (!segment.Include) return;
            if (!Enum.IsDefined(segment.Kind)) throw new UserFacingException("识别结果包含未知的段落类型，请重新选择类型。");
            string text = segment.Text ?? "";
            if (string.IsNullOrWhiteSpace(text)) return;
            if (text.Length > DocumentImporter.MaxTextCharacters) throw new UserFacingException("单个段落过长，请先拆分后导出。");
            included++;
            if (segment.Kind == SegmentKind.Direction && options.DirectionAsComments)
            {
                foreach (string line in DocumentImporter.NormalizeNewlines(text).Split('\n'))
                    result.Append(indent).Append("# 说明：").Append(CleanComment(line)).Append('\n');
            }
            else if (segment.Kind == SegmentKind.Dialogue)
            {
                string speaker = segment.Speaker?.Trim() ?? "";
                if (speaker.Length == 0)
                {
                    result.Append(indent).Append("# 待确认：原文第 ").Append(segment.Paragraph).Append(" 段的说话人未确定。\n");
                    result.Append(indent).Append("s \"").Append(Escape(text)).Append("\"\n");
                }
                else
                {
                    result.Append(indent);
                    if (options.CharacterVariables.TryGetValue(speaker, out string? variable)) result.Append(variable);
                    else result.Append(automaticVariables[speaker]);
                    result.Append(" \"").Append(Escape(text)).Append("\"\n");
                }
            }
            else result.Append(indent).Append("s \"").Append(Escape(text)).Append("\"\n");
            CheckOutputSize();
        }

        void EmitTree(ChoiceTree tree, string indent)
        {
            result.Append(indent).Append("menu:\n");
            if (!string.IsNullOrWhiteSpace(tree.Title))
                result.Append(indent).Append("    \"").Append(Escape(tree.Title)).Append("\"\n");
            foreach (var branch in tree.Branches)
            {
                result.Append(indent).Append("    \"").Append(Escape(branch.Label)).Append("\":\n");
                bool hasExecutableContent = false;
                foreach (var item in branch.Items)
                {
                    if (item.Segment is not null)
                    {
                        bool executable = item.Segment.Include && !string.IsNullOrWhiteSpace(item.Segment.Text) &&
                            (item.Segment.Kind != SegmentKind.Direction || !options.DirectionAsComments);
                        EmitSegment(item.Segment, indent + "        ");
                        hasExecutableContent |= executable;
                    }
                    else if (item.Tree is not null)
                    {
                        EmitTree(item.Tree, indent + "        ");
                        hasExecutableContent = true;
                    }
                }
                if (!hasExecutableContent) result.Append(indent).Append("        pass\n");
            }
            CheckOutputSize();
        }

        foreach (var segment in allSegments)
        {
            if (segment is null) throw new UserFacingException("识别结果包含无效段落，请重新解析。");
            if (before.TryGetValue(segment.Id, out var beforeTrees))
                foreach (var tree in beforeTrees) EmitTree(tree, "    ");
            EmitSegment(segment, "    ");
            if (after.TryGetValue(segment.Id, out var afterTrees))
                foreach (var tree in afterTrees) EmitTree(tree, "    ");
        }
        if (included == 0 && allTrees.Count == 0) throw new UserFacingException("没有可导出的内容。请确认至少有一个非空段落勾选了“导出”。");
        result.Append("\n    return\n");
        return result.ToString();
    }

    private static Dictionary<string, string> BuildCharacterVariables(
        IReadOnlyList<Segment> segments, IReadOnlyList<ChoiceTree> trees, ExportOptions options)
    {
        var variables = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var occupied = new HashSet<string>(options.CharacterVariables.Values, StringComparer.OrdinalIgnoreCase)
        {
            "s", options.Label, "narrator", "adv", "nvl", "name_only", "config", "renpy",
            "store", "persistent", "preferences", "gui", "style", "ui", "audio"
        };
        if (options.CharacterVariables.Values.Any(value => string.Equals(value, "s", StringComparison.OrdinalIgnoreCase)))
            throw new UserFacingException("角色变量 s 已用于无说话人的句子，请把该角色映射为其他变量名。");

        void Add(Segment? segment)
        {
            if (segment is null || !segment.Include || segment.Kind != SegmentKind.Dialogue ||
                string.IsNullOrWhiteSpace(segment.Text) || string.IsNullOrWhiteSpace(segment.Speaker)) return;
            var speaker = segment.Speaker.Trim();
            if (options.CharacterVariables.ContainsKey(speaker) || variables.ContainsKey(speaker)) return;
            var stem = CharacterIdentifier(speaker);
            var candidate = stem;
            for (var suffix = 2; occupied.Contains(candidate) || Reserved.Contains(candidate); suffix++)
                candidate = $"{stem}_{suffix}";
            variables.Add(speaker, candidate);
            occupied.Add(candidate);
        }

        void Visit(ChoiceTree tree)
        {
            foreach (var branch in tree.Branches)
                foreach (var item in branch.Items)
                    if (item.Segment is not null) Add(item.Segment);
                    else if (item.Tree is not null) Visit(item.Tree);
        }

        foreach (var segment in segments) Add(segment);
        foreach (var tree in trees) Visit(tree);
        return variables;
    }

    private static string CharacterIdentifier(string speaker)
    {
        var name = new StringBuilder();
        foreach (var character in speaker.Normalize(NormalizationForm.FormKC))
        {
            if (char.IsLetterOrDigit(character) || character == '_')
            {
                if (name.Length < 80) name.Append(character);
            }
            else if (name.Length > 0 && name[^1] != '_' && name.Length < 80) name.Append('_');
        }
        var result = name.ToString().Trim('_');
        if (result.Length == 0) return "character";
        return char.IsLetter(result[0]) ? result : "character_" + result;
    }

    public static void Write(string path, IEnumerable<Segment> segments, ExportOptions options, bool overwrite = false, IEnumerable<ChoiceTree>? choiceTrees = null)
    {
        string content = Generate(segments, options, choiceTrees);
        SafeFileWriter.Write(path, content, overwrite, "Ren’Py 剧本");
    }

    internal static void ValidateIdentifier(string? value, string caption)
    {
        if (value is null || !Identifier.IsMatch(value) || Reserved.Contains(value))
            throw new UserFacingException($"{caption}无效。请使用 1～128 位英文字母、数字和下划线，以字母或下划线开头，且不要使用 Python 或 Ren’Py 的保留字。");
    }

    // Ren'Py official escape rules: https://www.renpy.org/doc/html/text.html#escape-characters
    // Escape all text literally: source documents cannot inject interpolation or text tags.
    public static string Escape(string text)
    {
        var output = new StringBuilder();
        foreach (char c in DocumentImporter.NormalizeNewlines(text))
        {
            switch (c)
            {
                case '\\': output.Append("\\\\"); break;
                case '"': output.Append("\\\""); break;
                case '[': output.Append("[["); break;
                case '{': output.Append("{{"); break;
                case '%': output.Append("%%"); break;
                case '〖': output.Append("〖〖"); break;
                case '\n': output.Append("\\n"); break;
                case '\t': output.Append("\\ \\ \\ \\ "); break;
                case ' ': output.Append("\\ "); break;
                default:
                    if (char.IsControl(c)) throw new UserFacingException("文字包含无法导出的控制字符，请在预览中删除该字符后重试。");
                    output.Append(c); break;
            }
        }
        return output.ToString();
    }

    private static string CleanComment(string text) => new(text.Where(c => !char.IsControl(c) || c == '\t').ToArray());
}
